services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-data
    networks:
      mosquitto-net:
        ipv4_address: 192.168.100.2
    volumes:
      - "./mosquitto-data/config:/mosquitto/config"
      - "./mosquitto-data/data:/mosquitto/data"
      - "./mosquitto-data/log:/mosquitto/log"
    ports:
      - "1883:1883" # Expose port 1883 to the host
    command: mosquitto -c /mosquitto/config/mosquitto.conf


  postgres:
    container_name: postgres-container
    build:
      context: ./sql
      dockerfile: Dockerfile-db
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"


networks:
  mosquitto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24