services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-data
    networks:
      mosquitto-net:
        ipv4_address: 192.168.100.2
    volumes:
      - "./mosquitto-data/config:/mosquitto/config"
      - "./mosquitto-data/data:/mosquitto/data"
      - "./mosquitto-data/log:/mosquitto/log"
    ports:
      - "1883:1883" # Expose port 1883 to the host
    command: mosquitto -c /mosquitto/config/mosquitto.conf


  postgres:
    container_name: postgres-container
    build:
      context: ./sql
      dockerfile: Dockerfile-db
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  node-red:
      image: nodered/node-red:latest
      container_name: node-red
      environment:
        - TZ=Europe/Portugal
      ports:
        - 1880:1880
      networks:
        idc-net:
          ipv4_address: 172.100.10.15
      volumes:
        - ./data/node-red-data:/data


networks:
  idc-net:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.100.10.0/24

  mosquitto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24